# Default values for gateway.

controller:
  replicaCount: 1
  annotations: {}
  ## Limit the scope of the controller
  ##
  scope:
    enabled: false
    namespace: ""  # defaults to .Release.Namespace
  image:
    repository: kubesphere/ingress-nginx-controller
    tag: "v0.48.1"
    pullPolicy: IfNotPresent


service:
  ## annotations for Services, used for config Cloud LoadBalancer
  annotations: {}
  type: LoadBalancer

## for nginx controller, same with controller
deployment:
  annotations: {}
  replicaCount: 1